#pragma once
enum INVENSTATE { INVEN_IDLE, INVEN_OPEN, INVEN_STAY, INVEN_CLOSE, INVEN_END };
enum INVENTORY_RENDER_TYPE { INVENRT_RESOURCE, INVENRT_PLAYERINFO, INVENRT_END };
enum ITEM_RENDER_TYPE {IRT_IMAGE,IRT_COUNT,IRT_END};
